
// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

const prismaCliDatabaseUrl =
  // Allows `prisma generate` during dependency install before Vercel build envs
  // are available. Runtime, migrations, and builds still use real env vars.
  process.env.DATABASE_URL ??
  "postgresql://prisma:prisma@localhost:5432/prisma_generate";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  engine: "classic",
  datasource: {
    url: prismaCliDatabaseUrl,
  },
});
